version: '3'

networks:
  example:
services:
  nginx:
    image: nginx:alpine
    ports:
      - "8081:80"
  php:
    image: php:fpm-alpine
  apache2:
    image: php:7.4-apache
    container_name: ApacheWebServer
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
    networks:
      - example
  mysql:
    image: mysql:5.7.30
    container_name: MySQLDatabase
    restart: unless-stopped
    tty: true
    ports:
      - "4306:3306"
    volumes:
      - ./config/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - example
